sparql_endpoint: http://www.example.com/sparql/
sparul_endpoint: http://www.example.com/sparql-auth/
username: user
password: secret
auth_method: 'digest'
reviewgraph: 'http://www.example.com/reviews'
bookgraph: 'http://www.example.com/books'
apigraph: 'http://www.example.com/sources'
base_uri: 'http://data.deichman.no'
secret_session_key: 'averylonganimpossibletoguessstring'
